name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo install wasm-bindgen-cli
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --no-typescript --target web --out-dir ./docs/ ./target/wasm32-unknown-unknown/release/bevy_third_person_camera_example.wasm
